sudo: required

services:
  - docker


before_install:
  - docker build -t Yosshii001/docker-react -f Dockerfile.dev .

script:
  - docker run test Yosshii001/docker-react npm run test -- --coverage
  
